version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: black
    versions:
    - 21.4b0
    - 21.4b1
    - 21.4b2
  - dependency-name: datamodel-code-generator
    versions:
    - 0.10.0
    - 0.10.2
    - 0.10.3
    - 0.11.0
    - 0.11.1
    - 0.11.2
    - 0.6.26
    - 0.7.0
    - 0.7.1
    - 0.7.2
    - 0.7.3
    - 0.8.0
    - 0.9.0
    - 0.9.1
    - 0.9.2
    - 0.9.3
    - 0.9.4
  - dependency-name: isort
    versions:
    - 5.8.0
  - dependency-name: pydantic
    versions:
    - "1.8"
    - 1.8.1
  - dependency-name: pysnooper
    versions:
    - 0.4.3
