site_name: fastapi-code-generator
site_description: This code generator creates FastAPI app from an openapi file.

theme:
    name: 'material'
    palette:
      primary: 'light blue'
      accent: 'light blue'
    analytics:
      gtag: 275257853
markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: 🔗

repo_name: koxudaxi/fastapi-code-generator
repo_url: https://github.com/koxudaxi/fastapi-code-generator
site_url: https://koxudaxi.github.io/fastapi-code-generator

nav:
    - Overview: index.md
    - Development-Contributing: development-contributing.md

plugins:
  - search